bot:
  name: ${TELEGRAM_BOT_NAME}
  token: ${TELEGRAM_BOT_TOKEN}

owner:
  userName: Marandyuk_Anatolii

server:
  port: ${REVIEW_BOT_PORT}
  host: "https://overridetech.ru/review-report-bot"

reminders:
  maxDaysWithoutReport: 3

pay-info:
  login: ${LIFE_PAY_LOGIN}
  apikey: ${LIFE_PAY_KEY}
  method: sbp

spring:
  datasource:
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_USER}
    url: jdbc:postgresql://${REVIEW_BOT_DB_HOST:localhost}:${REVIEW_BOT_DB_PORT:5432}/${REVIEW_BOT_DB:review_bot}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: com.nekromant.telegram.utils.CustomDialectUtils # org.hibernate.dialect.PostgreSQL81Dialect
        show_sql: false
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
    generate-ddl: true

lombok:
  accessors:
    chain: true

schedulePeriod:
  start: 18
  end: 3