bot:
  name: ${TELEGRAM_BOT_NAME}
  token: ${TELEGRAM_BOT_TOKEN}

owner:
  userName: HomerTheBald


server:
  port: 9001
  host: "https://overridetech.ru/review-report-bot"

reminders:
  maxDaysWithoutReport: 3

pay-info:
  login: ${LIFE_PAY_LOGIN:test}
  apikey: ${LIFE_PAY_KEY:test}
  method: sbp

spring:
  datasource:
    password: ${POSTGRES_PASSWORD:root}
    username: ${POSTGRES_USER:root}
    url: jdbc:postgresql://${REVIEW_BOT_DB_HOST:review-bot-db}:5432/${REVIEW_BOT_DB:review_bot}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: com.nekromant.telegram.utils.CustomDialectUtils # org.hibernate.dialect.PostgreSQL81Dialect
        show_sql: false
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
    generate-ddl: true

lombok:
  accessors:
    chain: true

schedulePeriod:
  start: 18
  end: 3
